export {
	Pagination,
	PaginationContent,
	PaginationItem,
	PaginationLink,
	PaginationPrevious,
	PaginationNext,
	PaginationEllipsis,
	type PaginationProps,
	type PaginationContentProps,
	type PaginationItemProps,
	type PaginationLinkProps,
	type PaginationPreviousProps,
	type PaginationNextProps,
	type PaginationEllipsisProps,
} from './pagination';
