import type { PackageRegistryItem } from '@tile-ui/buildx/registry/types';

export const solidLibItems: PackageRegistryItem[] = [
	{
		name: 'liveline-core',
		type: 'registry:lib',
		title: 'Liveline Core',
		description: 'Framework-independent canvas engine, drawing, and math modules for Liveline.',
		files: [
			['index.ts', '@tile-ui/core/liveline'],
			['types.ts'],
			['theme.ts'],
			['engine.ts'],
			['canvas/dpr.ts'],
			['draw/badge.ts'],
			['draw/candlestick.ts'],
			['draw/crosshair.ts'],
			['draw/dot.ts'],
			['draw/empty.ts'],
			['draw/grid.ts'],
			['draw/index.ts'],
			['draw/line.ts'],
			['draw/loading.ts'],
			['draw/loadingShape.ts'],
			['draw/orderbook.ts'],
			['draw/particles.ts'],
			['draw/referenceLine.ts'],
			['draw/timeAxis.ts'],
			['math/interpolate.ts'],
			['math/intervals.ts'],
			['math/lerp.ts'],
			['math/momentum.ts'],
			['math/range.ts'],
			['math/spline.ts'],
		].map(([file, registryImport]) => ({
			source: `packages/core/src/liveline/${file}`,
			type: 'registry:lib' as const,
			transform: 'copy' as const,
			target: `components/ui/lib/liveline/${file}`,
			...(registryImport ? { registryImport } : {}),
		})),
	},
	{
		name: 'core',
		type: 'registry:lib',
		title: 'Core',
		description: 'Registry runtime types and component logic for SolidJS Tile UI items.',
		registryDependencies: ['@tile-ui/utils'],
		files: [
			{
				source: '__virtual__/shared/core.ts',
				type: 'registry:lib',
				transform: 'copy',
				target: 'components/ui/lib/core.ts',
			},
		],
	},
	{
		name: 'utils',
		type: 'registry:lib',
		title: 'Utils',
		description: 'Shared class, core, and SolidJS event utility helpers for Tile UI registries.',
		files: [
			{
				source: '__virtual__/shared/utils.ts',
				type: 'registry:lib',
				transform: 'copy',
				target: 'components/ui/lib/utils.ts',
			},
		],
	},
];
