import type { PackageRegistryItem } from '@tile-ui/buildx/registry/types';

const reactUiItemsBase: PackageRegistryItem[] = [
	{
		name: 'button',
		type: 'registry:ui',
		title: 'Button',
		description: 'Multi-variant React button component for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/utils'],
		files: [
			{
				source: 'packages/react/src/components/button/button.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/button.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/button/button.module.scss',
			},
		],
	},
	{
		name: 'input',
		type: 'registry:ui',
		title: 'Input',
		description: 'Accessible React input component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/utils'],
		files: [
			{
				source: 'packages/react/src/components/input/input.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/input.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/input/input.module.scss',
			},
		],
	},
	{
		name: 'textarea',
		type: 'registry:ui',
		title: 'Textarea',
		description: 'Accessible React textarea component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/utils'],
		files: [
			{
				source: 'packages/react/src/components/textarea/textarea.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/textarea.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/textarea/textarea.module.scss',
			},
		],
	},
	{
		name: 'label',
		type: 'registry:ui',
		title: 'Label',
		description: 'React label primitive for Tile UI forms.',
		dependencies: ['@radix-ui/react-label'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/label/label.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/label.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/label/label.module.scss',
			},
		],
	},
	{
		name: 'card',
		type: 'registry:ui',
		title: 'Card',
		description: 'Composable React card primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/card/card.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/card.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/card/card.module.scss',
			},
		],
	},
	{
		name: 'badge',
		type: 'registry:ui',
		title: 'Badge',
		description: 'Multi-variant React badge component for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/badge/badge.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/badge.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/badge/badge.module.scss',
			},
		],
	},
	{
		name: 'skeleton',
		type: 'registry:ui',
		title: 'Skeleton',
		description: 'Loading placeholder React component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/skeleton/skeleton.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/skeleton.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/skeleton/skeleton.module.scss',
			},
		],
	},
	{
		name: 'kbd',
		type: 'registry:ui',
		title: 'Kbd',
		description: 'Keyboard key display primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/kbd/kbd.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/kbd.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/kbd/kbd.module.scss',
			},
		],
	},
	{
		name: 'separator',
		type: 'registry:ui',
		title: 'Separator',
		description: 'Horizontal or vertical divider component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/separator/separator.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/separator.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/separator/separator.module.scss',
			},
		],
	},
	{
		name: 'table',
		type: 'registry:ui',
		title: 'Table',
		description: 'Composable React table primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/table/table.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/table.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/table/table.module.scss',
			},
		],
	},
	{
		name: 'progress',
		type: 'registry:ui',
		title: 'Progress',
		description: 'Progress bar component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/progress/progress.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/progress.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/progress/progress.module.scss',
			},
		],
	},
	{
		name: 'avatar',
		type: 'registry:ui',
		title: 'Avatar',
		description: 'User avatar primitives with image fallback for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/avatar/avatar.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/avatar.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/avatar/avatar.module.scss',
			},
		],
	},
	{
		name: 'switch',
		type: 'registry:ui',
		title: 'Switch',
		description: 'Accessible toggle switch component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/switch/switch.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/switch.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/switch/switch.module.scss',
			},
		],
	},
	{
		name: 'checkbox',
		type: 'registry:ui',
		title: 'Checkbox',
		description: 'Accessible checkbox with indeterminate state for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/checkbox/checkbox.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/checkbox.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/checkbox/checkbox.module.scss',
			},
		],
	},
	{
		name: 'collapsible',
		type: 'registry:ui',
		title: 'Collapsible',
		description: 'Accessible collapsible content component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/collapsible/collapsible.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/collapsible.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/collapsible/collapsible.module.scss',
			},
		],
	},
	{
		name: 'breadcrumb',
		type: 'registry:ui',
		title: 'Breadcrumb',
		description: 'Navigation breadcrumb primitives for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/breadcrumb/breadcrumb.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/breadcrumb.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/breadcrumb/breadcrumb.module.scss',
			},
		],
	},
	{
		name: 'pagination',
		type: 'registry:ui',
		title: 'Pagination',
		description: 'Navigation pagination primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/pagination/pagination.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/pagination.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/pagination/pagination.module.scss',
			},
		],
	},
	{
		name: 'alert',
		type: 'registry:ui',
		title: 'Alert',
		description: 'Alert banner primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/alert/alert.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/alert.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/alert/alert.module.scss',
			},
		],
	},
	{
		name: 'aspect-ratio',
		type: 'registry:ui',
		title: 'Aspect Ratio',
		description: 'Fixed-ratio content container for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/aspect-ratio/aspect-ratio.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/aspect-ratio.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/aspect-ratio/aspect-ratio.module.scss',
			},
		],
	},
	{
		name: 'spinner',
		type: 'registry:ui',
		title: 'Spinner',
		description: 'Loading spinner component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/spinner/spinner.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/spinner.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/spinner/spinner.module.scss',
			},
		],
	},
	{
		name: 'empty',
		type: 'registry:ui',
		title: 'Empty',
		description: 'Empty state primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/empty/empty.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/empty.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/empty/empty.module.scss',
			},
		],
	},
	{
		name: 'marker',
		type: 'registry:ui',
		title: 'Marker',
		description: 'Status marker component for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/marker/marker.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/marker.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/marker/marker.module.scss',
			},
		],
	},
	{
		name: 'item',
		type: 'registry:ui',
		title: 'Item',
		description: 'Composable list item primitives for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/item/item.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/item.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/item/item.module.scss',
			},
		],
	},
	{
		name: 'button-group',
		type: 'registry:ui',
		title: 'Button Group',
		description: 'Grouped button container for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/button-group/button-group.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/button-group.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/button-group/button-group.module.scss',
			},
		],
	},
	{
		name: 'input-group',
		type: 'registry:ui',
		title: 'Input Group',
		description: 'Composable input group primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'button'],
		files: [
			{
				source: 'packages/react/src/components/input-group/input-group.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/input-group.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/input-group/input-group.module.scss',
			},
		],
	},
	{
		name: 'native-select',
		type: 'registry:ui',
		title: 'Native Select',
		description: 'Native select with custom chevron for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/native-select/native-select.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/native-select.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/native-select/native-select.module.scss',
			},
		],
	},
	{
		name: 'field',
		type: 'registry:ui',
		title: 'Field',
		description: 'Field label/description/message wrapper for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/field/field.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/field.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/field/field.module.scss',
			},
		],
	},
	{
		name: 'toggle',
		type: 'registry:ui',
		title: 'Toggle',
		description: 'Toggle button with pressed state for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/toggle/toggle.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/toggle.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/toggle/toggle.module.scss',
			},
		],
	},
	{
		name: 'toggle-group',
		type: 'registry:ui',
		title: 'Toggle Group',
		description: 'Grouped toggle buttons for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/toggle-group/toggle-group.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/toggle-group.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/toggle-group/toggle-group.module.scss',
			},
		],
	},
	{
		name: 'tabs',
		type: 'registry:ui',
		title: 'Tabs',
		description: 'Tabs navigation primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/tabs/tabs.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/tabs.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/tabs/tabs.module.scss',
			},
		],
	},
	{
		name: 'accordion',
		type: 'registry:ui',
		title: 'Accordion',
		description: 'Collapsible accordion for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/accordion/accordion.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/accordion.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/accordion/accordion.module.scss',
			},
		],
	},
	{
		name: 'radio-group',
		type: 'registry:ui',
		title: 'Radio Group',
		description: 'Radio group selection for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/radio-group/radio-group.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/radio-group.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/radio-group/radio-group.module.scss',
			},
		],
	},
	{
		name: 'slider',
		type: 'registry:ui',
		title: 'Slider',
		description: 'Slider control for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/slider/slider.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/slider.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/slider/slider.module.scss',
			},
		],
	},
	{
		name: 'scroll-area',
		type: 'registry:ui',
		title: 'Scroll Area',
		description: 'Custom scroll area for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/scroll-area/scroll-area.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/scroll-area.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/scroll-area/scroll-area.module.scss',
			},
		],
	},
	{
		name: 'tooltip',
		type: 'registry:ui',
		title: 'Tooltip',
		description: 'Tooltip overlay for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/tooltip/tooltip.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/tooltip.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/tooltip/tooltip.module.scss',
			},
		],
	},
	{
		name: 'popover',
		type: 'registry:ui',
		title: 'Popover',
		description: 'Popover overlay for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/popover/popover.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/popover.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/popover/popover.module.scss',
			},
		],
	},
	{
		name: 'hover-card',
		type: 'registry:ui',
		title: 'Hover Card',
		description: 'Hover card overlay for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/hover-card/hover-card.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/hover-card.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/hover-card/hover-card.module.scss',
			},
		],
	},
	{
		name: 'dialog',
		type: 'registry:ui',
		title: 'Dialog',
		description: 'Modal dialog for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'button', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/dialog/dialog.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/dialog.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/dialog/dialog.module.scss',
			},
		],
	},
	{
		name: 'alert-dialog',
		type: 'registry:ui',
		title: 'Alert Dialog',
		description: 'Alert dialog for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'button', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/alert-dialog/alert-dialog.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/alert-dialog.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/alert-dialog/alert-dialog.module.scss',
			},
		],
	},
	{
		name: 'sheet',
		type: 'registry:ui',
		title: 'Sheet',
		description: 'Side sheet overlay for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/sheet/sheet.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/sheet.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/sheet/sheet.module.scss',
			},
		],
	},
	{
		name: 'dropdown-menu',
		type: 'registry:ui',
		title: 'Dropdown Menu',
		description: 'Dropdown menu with checkbox and radio items for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/dropdown-menu/dropdown-menu.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/dropdown-menu.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/dropdown-menu/dropdown-menu.module.scss',
			},
		],
	},
	{
		name: 'context-menu',
		type: 'registry:ui',
		title: 'Context Menu',
		description: 'Right-click context menu for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/context-menu/context-menu.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/context-menu.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/context-menu/context-menu.module.scss',
			},
		],
	},
	{
		name: 'menubar',
		type: 'registry:ui',
		title: 'Menubar',
		description: 'Horizontal menu bar for Tile UI.',
		dependencies: ['react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/menubar/menubar.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/menubar.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/menubar/menubar.module.scss',
			},
		],
	},
	{
		name: 'navigation-menu',
		type: 'registry:ui',
		title: 'Navigation Menu',
		description: 'Navigation menu with viewport for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/navigation-menu/navigation-menu.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/navigation-menu.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/navigation-menu/navigation-menu.module.scss',
			},
		],
	},
	{
		name: 'select',
		type: 'registry:ui',
		title: 'Select',
		description: 'Custom select dropdown for Tile UI.',
		dependencies: ['react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/select/select.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/select.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/select/select.module.scss',
			},
		],
	},
	{
		name: 'combobox',
		type: 'registry:ui',
		title: 'Combobox',
		description: 'Searchable combobox for Tile UI.',
		dependencies: ['react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/combobox/combobox.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/combobox.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/combobox/combobox.module.scss',
			},
		],
	},
	{
		name: 'command',
		type: 'registry:ui',
		title: 'Command',
		description: 'Command palette primitives for Tile UI.',
		dependencies: ['react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/command/command.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/command.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/command/command.module.scss',
			},
		],
	},
	{
		name: 'chart',
		type: 'registry:ui',
		title: 'Chart',
		description: 'Chart primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/chart/chart.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/chart.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/chart/chart.module.scss',
			},
		],
	},
	{
		name: 'calendar',
		type: 'registry:ui',
		title: 'Calendar',
		description: 'Calendar component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/calendar/calendar.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/calendar.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/calendar/calendar.module.scss',
			},
		],
	},
	{
		name: 'drawer',
		type: 'registry:ui',
		title: 'Drawer',
		description: 'Drawer overlay for Tile UI.',
		dependencies: ['@radix-ui/react-slot', 'react-dom'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', '@tile-ui/portal'],
		files: [
			{
				source: 'packages/react/src/components/drawer/drawer.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/drawer.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/drawer/drawer.module.scss',
			},
		],
	},
	{
		name: 'form',
		type: 'registry:ui',
		title: 'Form',
		description: 'Form primitives for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'label'],
		files: [
			{
				source: 'packages/react/src/components/form/form.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/form.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/form/form.module.scss',
			},
		],
	},
	{
		name: 'sidebar',
		type: 'registry:ui',
		title: 'Sidebar',
		description: 'Sidebar layout for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'button', 'input', 'separator', 'sheet', 'skeleton', 'tooltip'],
		files: [
			{
				source: 'packages/react/src/components/sidebar/sidebar.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/sidebar.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/sidebar/sidebar.module.scss',
			},
		],
	},
	{
		name: 'carousel',
		type: 'registry:ui',
		title: 'Carousel',
		description: 'Carousel component for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'button'],
		files: [
			{
				source: 'packages/react/src/components/carousel/carousel.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/carousel.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/carousel/carousel.module.scss',
			},
		],
	},
	{
		name: 'resizable',
		type: 'registry:ui',
		title: 'Resizable',
		description: 'Resizable panel group for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/resizable/resizable.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/resizable.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/resizable/resizable.module.scss',
			},
		],
	},
	{
		name: 'attachment',
		type: 'registry:ui',
		title: 'Attachment',
		description: 'Attachment primitives for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core', 'button'],
		files: [
			{
				source: 'packages/react/src/components/attachment/attachment.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/attachment.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/attachment/attachment.module.scss',
			},
		],
	},
	{
		name: 'bubble',
		type: 'registry:ui',
		title: 'Bubble',
		description: 'Bubble chat primitives for Tile UI.',
		dependencies: ['@radix-ui/react-slot'],
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/bubble/bubble.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/bubble.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/bubble/bubble.module.scss',
			},
		],
	},
	{
		name: 'direction',
		type: 'registry:ui',
		title: 'Direction',
		description: 'Direction provider for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/direction/direction.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/direction.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/direction/direction.module.scss',
			},
		],
	},
	{
		name: 'message',
		type: 'registry:ui',
		title: 'Message',
		description: 'Message primitives for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/message/message.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/message.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/message/message.module.scss',
			},
		],
	},
	{
		name: 'message-scroller',
		type: 'registry:ui',
		title: 'Message Scroller',
		description: 'Message scroller for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/message-scroller/message-scroller.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/message-scroller.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/message-scroller/message-scroller.module.scss',
			},
		],
	},
	{
		name: 'sonner',
		type: 'registry:ui',
		title: 'Sonner',
		description: 'Toast notifications for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/sonner/sonner.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/sonner.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/sonner/sonner.module.scss',
			},
		],
	},
	{
		name: 'input-otp',
		type: 'registry:ui',
		title: 'Input OTP',
		description: 'One-time password input for Tile UI.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/core'],
		files: [
			{
				source: 'packages/react/src/components/input-otp/input-otp.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/styles/scss/components/input-otp.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/input-otp/input-otp.module.scss',
			},
		],
	},
	{
		name: 'liveline',
		type: 'registry:ui',
		title: 'Liveline',
		description: 'Real-time React canvas chart with line, multi-series, candlestick, and market-data modes.',
		devDependencies: ['sass'],
		registryDependencies: ['@tile-ui/liveline-core'],
		files: [
			{
				source: 'packages/react/src/components/liveline/liveline.tsx',
				type: 'registry:ui',
				transform: 'react-component',
			},
			{
				source: 'packages/react/src/components/liveline/liveline-transition.tsx',
				type: 'registry:ui',
				transform: 'react-component',
				target: 'components/ui/liveline/liveline-transition.tsx',
			},
			{
				source: 'packages/styles/scss/components/liveline.module.scss',
				type: 'registry:file',
				transform: 'style',
				target: 'components/ui/liveline/liveline.module.scss',
			},
		],
	},
];

export const reactUiItems = reactUiItemsBase.map((item) => ({
	...item,
	registryDependencies: [...new Set([...(item.registryDependencies ?? []), '@tile-ui/styles'])],
	files: [
		...item.files,
		...(item.type === 'registry:ui'
			? [
					{
						source: `packages/react/src/components/${item.name}/index.ts`,
						type: 'registry:ui' as const,
						transform: 'react-barrel' as const,
					},
				]
			: []),
	],
}));
